spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: some
    username: some
    password: some
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8040